class PlaceItem {
  final String nameTr;
  final String nameEn;
  final bool isCity; // true if it is a Turkish city, false if it's a country

  const PlaceItem({
    required this.nameTr,
    required this.nameEn,
    this.isCity = false,
  });

  bool matches(String query) {
    final q = query.toLowerCase()
        .replaceAll('ı', 'i')
        .replaceAll('ğ', 'g')
        .replaceAll('ü', 'u')
        .replaceAll('ş', 's')
        .replaceAll('ö', 'o')
        .replaceAll('ç', 'c');
    
    final trNorm = nameTr.toLowerCase()
        .replaceAll('ı', 'i')
        .replaceAll('ğ', 'g')
        .replaceAll('ü', 'u')
        .replaceAll('ş', 's')
        .replaceAll('ö', 'o')
        .replaceAll('ç', 'c');
        
    final enNorm = nameEn.toLowerCase()
        .replaceAll('ı', 'i')
        .replaceAll('ğ', 'g')
        .replaceAll('ü', 'u')
        .replaceAll('ş', 's')
        .replaceAll('ö', 'o')
        .replaceAll('ç', 'c');

    return trNorm.contains(q) || enNorm.contains(q);
  }
}

class BirthPlaceData {
  BirthPlaceData._();

  static const List<PlaceItem> allPlaces = [
    // --- TURKEY CITIES (81) ---
    PlaceItem(nameTr: 'Adana', nameEn: 'Adana', isCity: true),
    PlaceItem(nameTr: 'Adıyaman', nameEn: 'Adiyaman', isCity: true),
    PlaceItem(nameTr: 'Afyonkarahisar', nameEn: 'Afyonkarahisar', isCity: true),
    PlaceItem(nameTr: 'Ağrı', nameEn: 'Agri', isCity: true),
    PlaceItem(nameTr: 'Amasya', nameEn: 'Amasya', isCity: true),
    PlaceItem(nameTr: 'Ankara', nameEn: 'Ankara', isCity: true),
    PlaceItem(nameTr: 'Antalya', nameEn: 'Antalya', isCity: true),
    PlaceItem(nameTr: 'Artvin', nameEn: 'Artvin', isCity: true),
    PlaceItem(nameTr: 'Aydın', nameEn: 'Aydin', isCity: true),
    PlaceItem(nameTr: 'Balıkesir', nameEn: 'Balikesir', isCity: true),
    PlaceItem(nameTr: 'Bilecik', nameEn: 'Bilecik', isCity: true),
    PlaceItem(nameTr: 'Bingöl', nameEn: 'Bingol', isCity: true),
    PlaceItem(nameTr: 'Bitlis', nameEn: 'Bitlis', isCity: true),
    PlaceItem(nameTr: 'Bolu', nameEn: 'Bolu', isCity: true),
    PlaceItem(nameTr: 'Burdur', nameEn: 'Burdur', isCity: true),
    PlaceItem(nameTr: 'Bursa', nameEn: 'Bursa', isCity: true),
    PlaceItem(nameTr: 'Çanakkale', nameEn: 'Canakkale', isCity: true),
    PlaceItem(nameTr: 'Çankırı', nameEn: 'Cankiri', isCity: true),
    PlaceItem(nameTr: 'Çorum', nameEn: 'Corum', isCity: true),
    PlaceItem(nameTr: 'Denizli', nameEn: 'Denizli', isCity: true),
    PlaceItem(nameTr: 'Diyarbakır', nameEn: 'Diyarbakir', isCity: true),
    PlaceItem(nameTr: 'Edirne', nameEn: 'Edirne', isCity: true),
    PlaceItem(nameTr: 'Elazığ', nameEn: 'Elazig', isCity: true),
    PlaceItem(nameTr: 'Erzincan', nameEn: 'Erzincan', isCity: true),
    PlaceItem(nameTr: 'Erzurum', nameEn: 'Erzurum', isCity: true),
    PlaceItem(nameTr: 'Eskişehir', nameEn: 'Eskisehir', isCity: true),
    PlaceItem(nameTr: 'Gaziantep', nameEn: 'Gaziantep', isCity: true),
    PlaceItem(nameTr: 'Giresun', nameEn: 'Giresun', isCity: true),
    PlaceItem(nameTr: 'Gümüşhane', nameEn: 'Gumushane', isCity: true),
    PlaceItem(nameTr: 'Hakkari', nameEn: 'Hakkari', isCity: true),
    PlaceItem(nameTr: 'Hatay', nameEn: 'Hatay', isCity: true),
    PlaceItem(nameTr: 'Isparta', nameEn: 'Isparta', isCity: true),
    PlaceItem(nameTr: 'Mersin', nameEn: 'Mersin', isCity: true),
    PlaceItem(nameTr: 'İstanbul', nameEn: 'Istanbul', isCity: true),
    PlaceItem(nameTr: 'İzmir', nameEn: 'Izmir', isCity: true),
    PlaceItem(nameTr: 'Kars', nameEn: 'Kars', isCity: true),
    PlaceItem(nameTr: 'Kastamonu', nameEn: 'Kastamonu', isCity: true),
    PlaceItem(nameTr: 'Kayseri', nameEn: 'Kayseri', isCity: true),
    PlaceItem(nameTr: 'Kırklareli', nameEn: 'Kirklareli', isCity: true),
    PlaceItem(nameTr: 'Kırşehir', nameEn: 'Kirsehir', isCity: true),
    PlaceItem(nameTr: 'Kocaeli', nameEn: 'Kocaeli', isCity: true),
    PlaceItem(nameTr: 'Konya', nameEn: 'Konya', isCity: true),
    PlaceItem(nameTr: 'Kütahya', nameEn: 'Kutahya', isCity: true),
    PlaceItem(nameTr: 'Malatya', nameEn: 'Malatya', isCity: true),
    PlaceItem(nameTr: 'Manisa', nameEn: 'Manisa', isCity: true),
    PlaceItem(nameTr: 'Kahramanmaraş', nameEn: 'Kahramanmaras', isCity: true),
    PlaceItem(nameTr: 'Mardin', nameEn: 'Mardin', isCity: true),
    PlaceItem(nameTr: 'Muğla', nameEn: 'Mugla', isCity: true),
    PlaceItem(nameTr: 'Muş', nameEn: 'Mus', isCity: true),
    PlaceItem(nameTr: 'Nevşehir', nameEn: 'Nevsehir', isCity: true),
    PlaceItem(nameTr: 'Niğde', nameEn: 'Nigde', isCity: true),
    PlaceItem(nameTr: 'Ordu', nameEn: 'Ordu', isCity: true),
    PlaceItem(nameTr: 'Rize', nameEn: 'Rize', isCity: true),
    PlaceItem(nameTr: 'Sakarya', nameEn: 'Sakarya', isCity: true),
    PlaceItem(nameTr: 'Samsun', nameEn: 'Samsun', isCity: true),
    PlaceItem(nameTr: 'Siirt', nameEn: 'Siirt', isCity: true),
    PlaceItem(nameTr: 'Sinop', nameEn: 'Sinop', isCity: true),
    PlaceItem(nameTr: 'Sivas', nameEn: 'Sivas', isCity: true),
    PlaceItem(nameTr: 'Tekirdağ', nameEn: 'Tekirdag', isCity: true),
    PlaceItem(nameTr: 'Tokat', nameEn: 'Tokat', isCity: true),
    PlaceItem(nameTr: 'Trabzon', nameEn: 'Trabzon', isCity: true),
    PlaceItem(nameTr: 'Tunceli', nameEn: 'Tunceli', isCity: true),
    PlaceItem(nameTr: 'Şanlıurfa', nameEn: 'Sanliurfa', isCity: true),
    PlaceItem(nameTr: 'Uşak', nameEn: 'Usak', isCity: true),
    PlaceItem(nameTr: 'Van', nameEn: 'Van', isCity: true),
    PlaceItem(nameTr: 'Yozgat', nameEn: 'Yozgat', isCity: true),
    PlaceItem(nameTr: 'Zonguldak', nameEn: 'Zonguldak', isCity: true),
    PlaceItem(nameTr: 'Aksaray', nameEn: 'Aksaray', isCity: true),
    PlaceItem(nameTr: 'Bayburt', nameEn: 'Bayburt', isCity: true),
    PlaceItem(nameTr: 'Karaman', nameEn: 'Karaman', isCity: true),
    PlaceItem(nameTr: 'Kırıkkale', nameEn: 'Kirikkale', isCity: true),
    PlaceItem(nameTr: 'Batman', nameEn: 'Batman', isCity: true),
    PlaceItem(nameTr: 'Şırnak', nameEn: 'Sirnak', isCity: true),
    PlaceItem(nameTr: 'Bartın', nameEn: 'Bartin', isCity: true),
    PlaceItem(nameTr: 'Ardahan', nameEn: 'Ardahan', isCity: true),
    PlaceItem(nameTr: 'Iğdır', nameEn: 'Igdir', isCity: true),
    PlaceItem(nameTr: 'Yalova', nameEn: 'Yalova', isCity: true),
    PlaceItem(nameTr: 'Karabük', nameEn: 'Karabuk', isCity: true),
    PlaceItem(nameTr: 'Kilis', nameEn: 'Kilis', isCity: true),
    PlaceItem(nameTr: 'Osmaniye', nameEn: 'Osmaniye', isCity: true),
    PlaceItem(nameTr: 'Düzce', nameEn: 'Duzce', isCity: true),

    // --- WORLD COUNTRIES (200+) ---
    PlaceItem(nameTr: 'Afganistan', nameEn: 'Afghanistan'),
    PlaceItem(nameTr: 'Almanya', nameEn: 'Germany'),
    PlaceItem(nameTr: 'Amerika Birleşik Devletleri', nameEn: 'United States'),
    PlaceItem(nameTr: 'Andorra', nameEn: 'Andorra'),
    PlaceItem(nameTr: 'Angola', nameEn: 'Angola'),
    PlaceItem(nameTr: 'Antigua ve Barbuda', nameEn: 'Antigua and Barbuda'),
    PlaceItem(nameTr: 'Arjantin', nameEn: 'Argentina'),
    PlaceItem(nameTr: 'Arnavutluk', nameEn: 'Albania'),
    PlaceItem(nameTr: 'Avustralya', nameEn: 'Australia'),
    PlaceItem(nameTr: 'Avusturya', nameEn: 'Austria'),
    PlaceItem(nameTr: 'Azerbaycan', nameEn: 'Azerbaijan'),
    PlaceItem(nameTr: 'Bahamalar', nameEn: 'Bahamas'),
    PlaceItem(nameTr: 'Bahreyn', nameEn: 'Bahrain'),
    PlaceItem(nameTr: 'Bangladeş', nameEn: 'Bangladesh'),
    PlaceItem(nameTr: 'Barbados', nameEn: 'Barbados'),
    PlaceItem(nameTr: 'Belçika', nameEn: 'Belgium'),
    PlaceItem(nameTr: 'Belize', nameEn: 'Belize'),
    PlaceItem(nameTr: 'Benin', nameEn: 'Benin'),
    PlaceItem(nameTr: 'Beyaz Rusya (Belarus)', nameEn: 'Belarus'),
    PlaceItem(nameTr: 'Bhutan', nameEn: 'Bhutan'),
    PlaceItem(nameTr: 'Birleşik Arap Emirlikleri', nameEn: 'United Arab Emirates'),
    PlaceItem(nameTr: 'Birleşik Krallık', nameEn: 'United Kingdom'),
    PlaceItem(nameTr: 'Bolivya', nameEn: 'Bolivia'),
    PlaceItem(nameTr: 'Bosna-Hersek', nameEn: 'Bosnia and Herzegovina'),
    PlaceItem(nameTr: 'Botsvana', nameEn: 'Botswana'),
    PlaceItem(nameTr: 'Brezilya', nameEn: 'Brazil'),
    PlaceItem(nameTr: 'Brunei', nameEn: 'Brunei'),
    PlaceItem(nameTr: 'Bulgaristan', nameEn: 'Bulgaria'),
    PlaceItem(nameTr: 'Burkina Faso', nameEn: 'Burkina Faso'),
    PlaceItem(nameTr: 'Burundi', nameEn: 'Burundi'),
    PlaceItem(nameTr: 'Cezayir', nameEn: 'Algeria'),
    PlaceItem(nameTr: 'Cibuti', nameEn: 'Djibouti'),
    PlaceItem(nameTr: 'Çad', nameEn: 'Chad'),
    PlaceItem(nameTr: 'Çek Cumhuriyeti (Çekya)', nameEn: 'Czechia'),
    PlaceItem(nameTr: 'Çin', nameEn: 'China'),
    PlaceItem(nameTr: 'Danimarka', nameEn: 'Denmark'),
    PlaceItem(nameTr: 'Doğu Timor', nameEn: 'East Timor'),
    PlaceItem(nameTr: 'Dominik Cumhuriyeti', nameEn: 'Dominican Republic'),
    PlaceItem(nameTr: 'Dominika', nameEn: 'Dominica'),
    PlaceItem(nameTr: 'Ekvador', nameEn: 'Ecuador'),
    PlaceItem(nameTr: 'Ekvator Ginesi', nameEn: 'Equatorial Guinea'),
    PlaceItem(nameTr: 'El Salvador', nameEn: 'El Salvador'),
    PlaceItem(nameTr: 'Endonezya', nameEn: 'Indonesia'),
    PlaceItem(nameTr: 'Eritre', nameEn: 'Eritrea'),
    PlaceItem(nameTr: 'Ermenistan', nameEn: 'Armenia'),
    PlaceItem(nameTr: 'Estonya', nameEn: 'Estonia'),
    PlaceItem(nameTr: 'Esvatini', nameEn: 'Eswatini'),
    PlaceItem(nameTr: 'Etiyopya', nameEn: 'Ethiopia'),
    PlaceItem(nameTr: 'Fas', nameEn: 'Morocco'),
    PlaceItem(nameTr: 'Fiji', nameEn: 'Fiji'),
    PlaceItem(nameTr: 'Fildişi Sahili', nameEn: 'Ivory Coast'),
    PlaceItem(nameTr: 'Filipinler', nameEn: 'Philippines'),
    PlaceItem(nameTr: 'Filistin', nameEn: 'Palestine'),
    PlaceItem(nameTr: 'Finlandiya', nameEn: 'Finland'),
    PlaceItem(nameTr: 'Fransa', nameEn: 'France'),
    PlaceItem(nameTr: 'Gabon', nameEn: 'Gabon'),
    PlaceItem(nameTr: 'Gambiya', nameEn: 'Gambia'),
    PlaceItem(nameTr: 'Gana', nameEn: 'Ghana'),
    PlaceItem(nameTr: 'Gine', nameEn: 'Guinea'),
    PlaceItem(nameTr: 'Gine-Bissau', nameEn: 'Guinea-Bissau'),
    PlaceItem(nameTr: 'Grenada', nameEn: 'Grenada'),
    PlaceItem(nameTr: 'Guatemala', nameEn: 'Guatemala'),
    PlaceItem(nameTr: 'Guyana', nameEn: 'Guyana'),
    PlaceItem(nameTr: 'Güney Afrika', nameEn: 'South Africa'),
    PlaceItem(nameTr: 'Güney Kore', nameEn: 'South Korea'),
    PlaceItem(nameTr: 'Güney Sudan', nameEn: 'South Sudan'),
    PlaceItem(nameTr: 'Gürcistan', nameEn: 'Georgia'),
    PlaceItem(nameTr: 'Haiti', nameEn: 'Haiti'),
    PlaceItem(nameTr: 'Hırvatistan', nameEn: 'Croatia'),
    PlaceItem(nameTr: 'Hindistan', nameEn: 'India'),
    PlaceItem(nameTr: 'Hollanda', nameEn: 'Netherlands'),
    PlaceItem(nameTr: 'Honduras', nameEn: 'Honduras'),
    PlaceItem(nameTr: 'Irak', nameEn: 'Iraq'),
    PlaceItem(nameTr: 'İran', nameEn: 'Iran'),
    PlaceItem(nameTr: 'İrlanda', nameEn: 'Ireland'),
    PlaceItem(nameTr: 'İspanya', nameEn: 'Spain'),
    PlaceItem(nameTr: 'İsrail', nameEn: 'Israel'),
    PlaceItem(nameTr: 'İsveç', nameEn: 'Sweden'),
    PlaceItem(nameTr: 'İsviçre', nameEn: 'Switzerland'),
    PlaceItem(nameTr: 'İtalya', nameEn: 'Italy'),
    PlaceItem(nameTr: 'İzlanda', nameEn: 'Iceland'),
    PlaceItem(nameTr: 'Jamaika', nameEn: 'Jamaica'),
    PlaceItem(nameTr: 'Japonya', nameEn: 'Japan'),
    PlaceItem(nameTr: 'Kamboçya', nameEn: 'Cambodia'),
    PlaceItem(nameTr: 'Kamerun', nameEn: 'Cameroon'),
    PlaceItem(nameTr: 'Kanada', nameEn: 'Canada'),
    PlaceItem(nameTr: 'Karadağ', nameEn: 'Montenegro'),
    PlaceItem(nameTr: 'Katar', nameEn: 'Qatar'),
    PlaceItem(nameTr: 'Kazakistan', nameEn: 'Kazakhstan'),
    PlaceItem(nameTr: 'Kenya', nameEn: 'Kenya'),
    PlaceItem(nameTr: 'Kırgızistan', nameEn: 'Kyrgyzstan'),
    PlaceItem(nameTr: 'Kiribati', nameEn: 'Kiribati'),
    PlaceItem(nameTr: 'Kolombiya', nameEn: 'Colombia'),
    PlaceItem(nameTr: 'Komorlar', nameEn: 'Comoros'),
    PlaceItem(nameTr: 'Kongo Cumhuriyeti', nameEn: 'Republic of the Congo'),
    PlaceItem(nameTr: 'Kongo Demokratik Cumhuriyeti', nameEn: 'DR Congo'),
    PlaceItem(nameTr: 'Kosova', nameEn: 'Kosovo'),
    PlaceItem(nameTr: 'Kosta Rika', nameEn: 'Costa Rica'),
    PlaceItem(nameTr: 'Kuveyt', nameEn: 'Kuwait'),
    PlaceItem(nameTr: 'Kuzey Kore', nameEn: 'North Korea'),
    PlaceItem(nameTr: 'Kuzey Makedonya', nameEn: 'North Macedonia'),
    PlaceItem(nameTr: 'Küba', nameEn: 'Cuba'),
    PlaceItem(nameTr: 'Laos', nameEn: 'Laos'),
    PlaceItem(nameTr: 'Lesotho', nameEn: 'Lesotho'),
    PlaceItem(nameTr: 'Letonya', nameEn: 'Latvia'),
    PlaceItem(nameTr: 'Liberya', nameEn: 'Liberia'),
    PlaceItem(nameTr: 'Libya', nameEn: 'Libya'),
    PlaceItem(nameTr: 'Liechtenstein', nameEn: 'Liechtenstein'),
    PlaceItem(nameTr: 'Litvanya', nameEn: 'Lithuania'),
    PlaceItem(nameTr: 'Lübnan', nameEn: 'Lebanon'),
    PlaceItem(nameTr: 'Lüksemburg', nameEn: 'Luxembourg'),
    PlaceItem(nameTr: 'Macaristan', nameEn: 'Hungary'),
    PlaceItem(nameTr: 'Madagaskar', nameEn: 'Madagascar'),
    PlaceItem(nameTr: 'Makao', nameEn: 'Macau'),
    PlaceItem(nameTr: 'Malavi', nameEn: 'Malawi'),
    PlaceItem(nameTr: 'Maldivler', nameEn: 'Maldives'),
    PlaceItem(nameTr: 'Malezya', nameEn: 'Malaysia'),
    PlaceItem(nameTr: 'Mali', nameEn: 'Mali'),
    PlaceItem(nameTr: 'Malta', nameEn: 'Malta'),
    PlaceItem(nameTr: 'Marshall Adaları', nameEn: 'Marshall Islands'),
    PlaceItem(nameTr: 'Mauritius', nameEn: 'Mauritius'),
    PlaceItem(nameTr: 'Meksika', nameEn: 'Mexico'),
    PlaceItem(nameTr: 'Mısır', nameEn: 'Egypt'),
    PlaceItem(nameTr: 'Mikronezya', nameEn: 'Micronesia'),
    PlaceItem(nameTr: 'Moğolistan', nameEn: 'Mongolia'),
    PlaceItem(nameTr: 'Moldova', nameEn: 'Moldova'),
    PlaceItem(nameTr: 'Monako', nameEn: 'Monaco'),
    PlaceItem(nameTr: 'Moritanya', nameEn: 'Mauritania'),
    PlaceItem(nameTr: 'Mozambik', nameEn: 'Mozambique'),
    PlaceItem(nameTr: 'Myanmar', nameEn: 'Myanmar'),
    PlaceItem(nameTr: 'Namibya', nameEn: 'Namibia'),
    PlaceItem(nameTr: 'Nauru', nameEn: 'Nauru'),
    PlaceItem(nameTr: 'Nepal', nameEn: 'Nepal'),
    PlaceItem(nameTr: 'Nikaragua', nameEn: 'Nicaragua'),
    PlaceItem(nameTr: 'Nijer', nameEn: 'Niger'),
    PlaceItem(nameTr: 'Nijerya', nameEn: 'Nigeria'),
    PlaceItem(nameTr: 'Norveç', nameEn: 'Norway'),
    PlaceItem(nameTr: 'Orta Afrika Cumhuriyeti', nameEn: 'Central African Republic'),
    PlaceItem(nameTr: 'Özbekistan', nameEn: 'Uzbekistan'),
    PlaceItem(nameTr: 'Pakistan', nameEn: 'Pakistan'),
    PlaceItem(nameTr: 'Palau', nameEn: 'Palau'),
    PlaceItem(nameTr: 'Panama', nameEn: 'Panama'),
    PlaceItem(nameTr: 'Papua Yeni Gine', nameEn: 'Papua New Guinea'),
    PlaceItem(nameTr: 'Paraguay', nameEn: 'Paraguay'),
    PlaceItem(nameTr: 'Peru', nameEn: 'Peru'),
    PlaceItem(nameTr: 'Polonya', nameEn: 'Poland'),
    PlaceItem(nameTr: 'Portekiz', nameEn: 'Portugal'),
    PlaceItem(nameTr: 'Romanya', nameEn: 'Romania'),
    PlaceItem(nameTr: 'Ruanda', nameEn: 'Rwanda'),
    PlaceItem(nameTr: 'Rusya', nameEn: 'Russia'),
    PlaceItem(nameTr: 'Saint Kitts ve Nevis', nameEn: 'Saint Kitts and Nevis'),
    PlaceItem(nameTr: 'Saint Lucia', nameEn: 'Saint Lucia'),
    PlaceItem(nameTr: 'Saint Vincent ve Grenadinler', nameEn: 'Saint Vincent and the Grenadines'),
    PlaceItem(nameTr: 'Samoa', nameEn: 'Samoa'),
    PlaceItem(nameTr: 'San Marino', nameEn: 'San Marino'),
    PlaceItem(nameTr: 'Sao Tome ve Principe', nameEn: 'Sao Tome and Principe'),
    PlaceItem(nameTr: 'Senegal', nameEn: 'Senegal'),
    PlaceItem(nameTr: 'Seyşeller', nameEn: 'Seychelles'),
    PlaceItem(nameTr: 'Sırbistan', nameEn: 'Serbia'),
    PlaceItem(nameTr: 'Sierra Leone', nameEn: 'Sierra Leone'),
    PlaceItem(nameTr: 'Singapur', nameEn: 'Singapore'),
    PlaceItem(nameTr: 'Slovakya', nameEn: 'Slovakia'),
    PlaceItem(nameTr: 'Slovenya', nameEn: 'Slovenia'),
    PlaceItem(nameTr: 'Somali', nameEn: 'Somalia'),
    PlaceItem(nameTr: 'Sri Lanka', nameEn: 'Sri Lanka'),
    PlaceItem(nameTr: 'Sudan', nameEn: 'Sudan'),
    PlaceItem(nameTr: 'Surinam', nameEn: 'Suriname'),
    PlaceItem(nameTr: 'Suriye', nameEn: 'Syria'),
    PlaceItem(nameTr: 'Suudi Arabistan', nameEn: 'Saudi Arabia'),
    PlaceItem(nameTr: 'Şili', nameEn: 'Chile'),
    PlaceItem(nameTr: 'Tacikistan', nameEn: 'Tajikistan'),
    PlaceItem(nameTr: 'Tanzanya', nameEn: 'Tanzania'),
    PlaceItem(nameTr: 'Tayland', nameEn: 'Thailand'),
    PlaceItem(nameTr: 'Tayvan', nameEn: 'Taiwan'),
    PlaceItem(nameTr: 'Togo', nameEn: 'Togo'),
    PlaceItem(nameTr: 'Tonga', nameEn: 'Tonga'),
    PlaceItem(nameTr: 'Trinidad ve Tobago', nameEn: 'Trinidad and Tobago'),
    PlaceItem(nameTr: 'Tunus', nameEn: 'Tunisia'),
    PlaceItem(nameTr: 'Tuvalu', nameEn: 'Tuvalu'),
    PlaceItem(nameTr: 'Türkiye', nameEn: 'Turkey'),
    PlaceItem(nameTr: 'Türkmenistan', nameEn: 'Turkmenistan'),
    PlaceItem(nameTr: 'Uganda', nameEn: 'Uganda'),
    PlaceItem(nameTr: 'Ukrayna', nameEn: 'Ukraine'),
    PlaceItem(nameTr: 'Umman', nameEn: 'Oman'),
    PlaceItem(nameTr: 'Uruguay', nameEn: 'Uruguay'),
    PlaceItem(nameTr: 'Ürdün', nameEn: 'Jordan'),
    PlaceItem(nameTr: 'Vanuatu', nameEn: 'Vanuatu'),
    PlaceItem(nameTr: 'Vatikan', nameEn: 'Vatican City'),
    PlaceItem(nameTr: 'Venezuela', nameEn: 'Venezuela'),
    PlaceItem(nameTr: 'Vietnam', nameEn: 'Vietnam'),
    PlaceItem(nameTr: 'Yemen', nameEn: 'Yemen'),
    PlaceItem(nameTr: 'Yeni Zelanda', nameEn: 'New Zealand'),
    PlaceItem(nameTr: 'Yunanistan', nameEn: 'Greece'),
    PlaceItem(nameTr: 'Zambiya', nameEn: 'Zambia'),
    PlaceItem(nameTr: 'Zimbabve', nameEn: 'Zimbabwe'),
  ];
}
