// File generated by FlutterFire CLI skeleton with placeholder configurations.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// TODO: Replace with real Firebase config
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-FAKE-KEY-WEB-HOROSCOPE',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'horoscope-app-fake',
    authDomain: 'horoscope-app-fake.firebaseapp.com',
    storageBucket: 'horoscope-app-fake.firebasestorage.app',
    measurementId: 'G-FAKEWEBID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsDFB0xLtW4kvhUUQHQ9W2DIbeGt8c3t4',
    appId: '1:809913113584:android:59762fa1e5cc586c1d9b35',
    messagingSenderId: '809913113584',
    projectId: 'horoscope-be21b',
    storageBucket: 'horoscope-be21b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmCljItROsMS8BSzyRVMDA_Z7e7dpobTQ',
    appId: '1:809913113584:ios:d8ecfb4778647dcf1d9b35',
    messagingSenderId: '809913113584',
    projectId: 'horoscope-be21b',
    storageBucket: 'horoscope-be21b.firebasestorage.app',
    iosBundleId: 'com.cervus.horoscope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt-FAKE-KEY-IOS-HOROSCOPE',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'horoscope-app-fake',
    storageBucket: 'horoscope-app-fake.firebasestorage.app',
    iosBundleId: 'com.cervus.horoscope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt-FAKE-KEY-WEB-HOROSCOPE',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'horoscope-app-fake',
    authDomain: 'horoscope-app-fake.firebaseapp.com',
    storageBucket: 'horoscope-app-fake.firebasestorage.app',
    measurementId: 'G-FAKEWINID',
  );
}