class TarotCard {
  final int id;
  final String nameTr;
  final String nameEn;
  final String symbol;
  final String astrologicalAssociationTr;
  final String astrologicalAssociationEn;

  const TarotCard({
    required this.id,
    required this.nameTr,
    required this.nameEn,
    required this.symbol,
    required this.astrologicalAssociationTr,
    required this.astrologicalAssociationEn,
  });

  /// 22 Major Arcana Tarot Kartı Listesi (Astrolojik İlişkileriyle Birlikte)
  static const List<TarotCard> majorArcana = [
    TarotCard(
      id: 0,
      nameTr: 'Deli (The Fool)',
      nameEn: 'The Fool',
      symbol: '🌀',
      astrologicalAssociationTr: 'Uranüs / Hava Elementi',
      astrologicalAssociationEn: 'Uranus / Air Element',
    ),
    TarotCard(
      id: 1,
      nameTr: 'Büyücü (The Magician)',
      nameEn: 'The Magician',
      symbol: '🪄',
      astrologicalAssociationTr: 'Merkür',
      astrologicalAssociationEn: 'Mercury',
    ),
    TarotCard(
      id: 2,
      nameTr: 'Azize (The High Priestess)',
      nameEn: 'The High Priestess',
      symbol: '🌙',
      astrologicalAssociationTr: 'Ay',
      astrologicalAssociationEn: 'Moon',
    ),
    TarotCard(
      id: 3,
      nameTr: 'İmparatoriçe (The Empress)',
      nameEn: 'The Empress',
      symbol: '👑',
      astrologicalAssociationTr: 'Venüs',
      astrologicalAssociationEn: 'Venus',
    ),
    TarotCard(
      id: 4,
      nameTr: 'İmparator (The Emperor)',
      nameEn: 'The Emperor',
      symbol: '🤴',
      astrologicalAssociationTr: 'Koç / Mars',
      astrologicalAssociationEn: 'Aries / Mars',
    ),
    TarotCard(
      id: 5,
      nameTr: 'Aziz (The Hierophant)',
      nameEn: 'The Hierophant',
      symbol: '⛪',
      astrologicalAssociationTr: 'Boğa / Venüs',
      astrologicalAssociationEn: 'Taurus / Venus',
    ),
    TarotCard(
      id: 6,
      nameTr: 'Aşıklar (The Lovers)',
      nameEn: 'The Lovers',
      symbol: '💑',
      astrologicalAssociationTr: 'İkizler / Merkür',
      astrologicalAssociationEn: 'Gemini / Mercury',
    ),
    TarotCard(
      id: 7,
      nameTr: 'Araba (The Chariot)',
      nameEn: 'The Chariot',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Yengeç / Ay',
      astrologicalAssociationEn: 'Cancer / Moon',
    ),
    TarotCard(
      id: 8,
      nameTr: 'Güç (Strength)',
      nameEn: 'Strength',
      symbol: '🦁',
      astrologicalAssociationTr: 'Aslan / Güneş',
      astrologicalAssociationEn: 'Leo / Sun',
    ),
    TarotCard(
      id: 9,
      nameTr: 'Ermiş (The Hermit)',
      nameEn: 'The Hermit',
      symbol: '🕯️',
      astrologicalAssociationTr: 'Başak / Merkür',
      astrologicalAssociationEn: 'Virgo / Mercury',
    ),
    TarotCard(
      id: 10,
      nameTr: 'Kader Çarkı (Wheel of Fortune)',
      nameEn: 'Wheel of Fortune',
      symbol: '🎡',
      astrologicalAssociationTr: 'Jüpiter',
      astrologicalAssociationEn: 'Jupiter',
    ),
    TarotCard(
      id: 11,
      nameTr: 'Adalet (Justice)',
      nameEn: 'Justice',
      symbol: '⚖️',
      astrologicalAssociationTr: 'Terazi / Venüs',
      astrologicalAssociationEn: 'Libra / Venus',
    ),
    TarotCard(
      id: 12,
      nameTr: 'Asılı Adam (The Hanged Man)',
      nameEn: 'The Hanged Man',
      symbol: '🤸',
      astrologicalAssociationTr: 'Neptün / Su Elementi',
      astrologicalAssociationEn: 'Neptune / Water Element',
    ),
    TarotCard(
      id: 13,
      nameTr: 'Ölüm (Death)',
      nameEn: 'Death',
      symbol: '💀',
      astrologicalAssociationTr: 'Akrep / Plüton',
      astrologicalAssociationEn: 'Scorpio / Pluto',
    ),
    TarotCard(
      id: 14,
      nameTr: 'Denge (Temperance)',
      nameEn: 'Temperance',
      symbol: '🏺',
      astrologicalAssociationTr: 'Yay / Jüpiter',
      astrologicalAssociationEn: 'Sagittarius / Jupiter',
    ),
    TarotCard(
      id: 15,
      nameTr: 'Şeytan (The Devil)',
      nameEn: 'The Devil',
      symbol: '😈',
      astrologicalAssociationTr: 'Oğlak / Satürn',
      astrologicalAssociationEn: 'Capricorn / Saturn',
    ),
    TarotCard(
      id: 16,
      nameTr: 'Yıkılan Kule (The Tower)',
      nameEn: 'The Tower',
      symbol: '💥',
      astrologicalAssociationTr: 'Mars',
      astrologicalAssociationEn: 'Mars',
    ),
    TarotCard(
      id: 17,
      nameTr: 'Yıldız (The Star)',
      nameEn: 'The Star',
      symbol: '⭐',
      astrologicalAssociationTr: 'Kova / Uranüs',
      astrologicalAssociationEn: 'Aquarius / Uranus',
    ),
    TarotCard(
      id: 18,
      nameTr: 'Ay (The Moon)',
      nameEn: 'The Moon',
      symbol: '🌕',
      astrologicalAssociationTr: 'Balık / Neptün',
      astrologicalAssociationEn: 'Pisces / Neptune',
    ),
    TarotCard(
      id: 19,
      nameTr: 'Güneş (The Sun)',
      nameEn: 'The Sun',
      symbol: '☀️',
      astrologicalAssociationTr: 'Güneş',
      astrologicalAssociationEn: 'Sun',
    ),
    TarotCard(
      id: 20,
      nameTr: 'Mahkeme (Judgement)',
      nameEn: 'Judgement',
      symbol: '🔔',
      astrologicalAssociationTr: 'Plüton / Ateş Elementi',
      astrologicalAssociationEn: 'Pluto / Fire Element',
    ),
    TarotCard(
      id: 21,
      nameTr: 'Dünya (The World)',
      nameEn: 'The World',
      symbol: '🌍',
      astrologicalAssociationTr: 'Satürn',
      astrologicalAssociationEn: 'Saturn',
    ),
  ];
}
