class TarotCard {
  final int id;
  final String nameTr;
  final String nameEn;
  final String symbol;
  final String astrologicalAssociationTr;
  final String astrologicalAssociationEn;
  final String suit; // 'major', 'cups', 'pentacles', 'swords', 'wands'
  final String imageName; // e.g. '0.jpg' or 'cups01.jpg'
  final bool isMajor;

  const TarotCard({
    required this.id,
    required this.nameTr,
    required this.nameEn,
    required this.symbol,
    required this.astrologicalAssociationTr,
    required this.astrologicalAssociationEn,
    required this.suit,
    required this.imageName,
    required this.isMajor,
  });

  /// ID ile kart bulur
  static TarotCard getCardById(int id) {
    return allCards.firstWhere((card) => card.id == id, orElse: () => allCards.first);
  }

  /// 22 Major Arcana Tarot Kartı Listesi
  static const List<TarotCard> majorArcana = [
    TarotCard(
      id: 0,
      nameTr: 'Deli (The Fool)',
      nameEn: 'The Fool',
      symbol: '🌀',
      astrologicalAssociationTr: 'Uranüs / Hava Elementi',
      astrologicalAssociationEn: 'Uranus / Air Element',
      suit: 'major',
      imageName: '0.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 1,
      nameTr: 'Büyücü (The Magician)',
      nameEn: 'The Magician',
      symbol: '🪄',
      astrologicalAssociationTr: 'Merkür',
      astrologicalAssociationEn: 'Mercury',
      suit: 'major',
      imageName: '1.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 2,
      nameTr: 'Azize (The High Priestess)',
      nameEn: 'The High Priestess',
      symbol: '🌙',
      astrologicalAssociationTr: 'Ay',
      astrologicalAssociationEn: 'Moon',
      suit: 'major',
      imageName: '2.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 3,
      nameTr: 'İmparatoriçe (The Empress)',
      nameEn: 'The Empress',
      symbol: '👑',
      astrologicalAssociationTr: 'Venüs',
      astrologicalAssociationEn: 'Venus',
      suit: 'major',
      imageName: '3.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 4,
      nameTr: 'İmparator (The Emperor)',
      nameEn: 'The Emperor',
      symbol: '🤴',
      astrologicalAssociationTr: 'Koç / Mars',
      astrologicalAssociationEn: 'Aries / Mars',
      suit: 'major',
      imageName: '4.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 5,
      nameTr: 'Aziz (The Hierophant)',
      nameEn: 'The Hierophant',
      symbol: '⛪',
      astrologicalAssociationTr: 'Boğa / Venüs',
      astrologicalAssociationEn: 'Taurus / Venus',
      suit: 'major',
      imageName: '5.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 6,
      nameTr: 'Aşıklar (The Lovers)',
      nameEn: 'The Lovers',
      symbol: '💑',
      astrologicalAssociationTr: 'İkizler / Merkür',
      astrologicalAssociationEn: 'Gemini / Mercury',
      suit: 'major',
      imageName: '6.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 7,
      nameTr: 'Araba (The Chariot)',
      nameEn: 'The Chariot',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Yengeç / Ay',
      astrologicalAssociationEn: 'Cancer / Moon',
      suit: 'major',
      imageName: '7.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 8,
      nameTr: 'Güç (Strength)',
      nameEn: 'Strength',
      symbol: '🦁',
      astrologicalAssociationTr: 'Aslan / Güneş',
      astrologicalAssociationEn: 'Leo / Sun',
      suit: 'major',
      imageName: '8.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 9,
      nameTr: 'Ermiş (The Hermit)',
      nameEn: 'The Hermit',
      symbol: '🕯️',
      astrologicalAssociationTr: 'Başak / Merkür',
      astrologicalAssociationEn: 'Virgo / Mercury',
      suit: 'major',
      imageName: '9.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 10,
      nameTr: 'Kader Çarkı (Wheel of Fortune)',
      nameEn: 'Wheel of Fortune',
      symbol: '🎡',
      astrologicalAssociationTr: 'Jüpiter',
      astrologicalAssociationEn: 'Jupiter',
      suit: 'major',
      imageName: '10.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 11,
      nameTr: 'Adalet (Justice)',
      nameEn: 'Justice',
      symbol: '⚖️',
      astrologicalAssociationTr: 'Terazi / Venüs',
      astrologicalAssociationEn: 'Libra / Venus',
      suit: 'major',
      imageName: '11.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 12,
      nameTr: 'Asılı Adam (The Hanged Man)',
      nameEn: 'The Hanged Man',
      symbol: '🤸',
      astrologicalAssociationTr: 'Neptün / Su Elementi',
      astrologicalAssociationEn: 'Neptune / Water Element',
      suit: 'major',
      imageName: '12.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 13,
      nameTr: 'Ölüm (Death)',
      nameEn: 'Death',
      symbol: '💀',
      astrologicalAssociationTr: 'Akrep / Plüton',
      astrologicalAssociationEn: 'Scorpio / Pluto',
      suit: 'major',
      imageName: '13.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 14,
      nameTr: 'Denge (Temperance)',
      nameEn: 'Temperance',
      symbol: '🏺',
      astrologicalAssociationTr: 'Yay / Jüpiter',
      astrologicalAssociationEn: 'Sagittarius / Jupiter',
      suit: 'major',
      imageName: '14.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 15,
      nameTr: 'Şeytan (The Devil)',
      nameEn: 'The Devil',
      symbol: '😈',
      astrologicalAssociationTr: 'Oğlak / Satürn',
      astrologicalAssociationEn: 'Capricorn / Saturn',
      suit: 'major',
      imageName: '15.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 16,
      nameTr: 'Yıkılan Kule (The Tower)',
      nameEn: 'The Tower',
      symbol: '💥',
      astrologicalAssociationTr: 'Mars',
      astrologicalAssociationEn: 'Mars',
      suit: 'major',
      imageName: '16.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 17,
      nameTr: 'Yıldız (The Star)',
      nameEn: 'The Star',
      symbol: '⭐',
      astrologicalAssociationTr: 'Kova / Uranüs',
      astrologicalAssociationEn: 'Aquarius / Uranus',
      suit: 'major',
      imageName: '17.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 18,
      nameTr: 'Ay (The Moon)',
      nameEn: 'The Moon',
      symbol: '🌕',
      astrologicalAssociationTr: 'Balık / Neptün',
      astrologicalAssociationEn: 'Pisces / Neptune',
      suit: 'major',
      imageName: '18.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 19,
      nameTr: 'Güneş (The Sun)',
      nameEn: 'The Sun',
      symbol: '☀️',
      astrologicalAssociationTr: 'Güneş',
      astrologicalAssociationEn: 'Sun',
      suit: 'major',
      imageName: '19.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 20,
      nameTr: 'Mahkeme (Judgement)',
      nameEn: 'Judgement',
      symbol: '🔔',
      astrologicalAssociationTr: 'Plüton / Ateş Elementi',
      astrologicalAssociationEn: 'Pluto / Fire Element',
      suit: 'major',
      imageName: '20.jpg',
      isMajor: true,
    ),
    TarotCard(
      id: 21,
      nameTr: 'Dünya (The World)',
      nameEn: 'The World',
      symbol: '🌍',
      astrologicalAssociationTr: 'Satürn',
      astrologicalAssociationEn: 'Saturn',
      suit: 'major',
      imageName: '21.jpg',
      isMajor: true,
    ),
  ];

  /// 56 Minor Arcana Tarot Kartı Listesi
  static const List<TarotCard> minorArcana = [
    // ── KUPALAR (CUPS) ──
    TarotCard(
      id: 22,
      nameTr: 'Kupa Ası',
      nameEn: 'Ace of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Su Elementi',
      astrologicalAssociationEn: 'Water Element',
      suit: 'cups',
      imageName: 'cups01.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 23,
      nameTr: 'Kupa İkilisi',
      nameEn: 'Two of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Yengeç',
      astrologicalAssociationEn: 'Cancer',
      suit: 'cups',
      imageName: 'cups02.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 24,
      nameTr: 'Kupa Üçlüsü',
      nameEn: 'Three of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Akrep',
      astrologicalAssociationEn: 'Scorpio',
      suit: 'cups',
      imageName: 'cups03.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 25,
      nameTr: 'Kupa Dörtlüsü',
      nameEn: 'Four of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Yengeç',
      astrologicalAssociationEn: 'Cancer',
      suit: 'cups',
      imageName: 'cups04.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 26,
      nameTr: 'Kupa Beşlisi',
      nameEn: 'Five of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Akrep',
      astrologicalAssociationEn: 'Scorpio',
      suit: 'cups',
      imageName: 'cups05.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 27,
      nameTr: 'Kupa Altılısı',
      nameEn: 'Six of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Balık',
      astrologicalAssociationEn: 'Pisces',
      suit: 'cups',
      imageName: 'cups06.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 28,
      nameTr: 'Kupa Yedilisi',
      nameEn: 'Seven of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Yengeç',
      astrologicalAssociationEn: 'Cancer',
      suit: 'cups',
      imageName: 'cups07.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 29,
      nameTr: 'Kupa Sekizlisi',
      nameEn: 'Eight of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Akrep',
      astrologicalAssociationEn: 'Scorpio',
      suit: 'cups',
      imageName: 'cups08.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 30,
      nameTr: 'Kupa Dokuzlusu',
      nameEn: 'Nine of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Balık',
      astrologicalAssociationEn: 'Pisces',
      suit: 'cups',
      imageName: 'cups09.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 31,
      nameTr: 'Kupa Onlusu',
      nameEn: 'Ten of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Balık',
      astrologicalAssociationEn: 'Pisces',
      suit: 'cups',
      imageName: 'cups10.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 32,
      nameTr: 'Kupa Uşağı',
      nameEn: 'Page of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Su Elementi',
      astrologicalAssociationEn: 'Water Element',
      suit: 'cups',
      imageName: 'cups11.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 33,
      nameTr: 'Kupa Şövalyesi',
      nameEn: 'Knight of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Akrep',
      astrologicalAssociationEn: 'Scorpio',
      suit: 'cups',
      imageName: 'cups12.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 34,
      nameTr: 'Kupa Kraliçesi',
      nameEn: 'Queen of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Yengeç',
      astrologicalAssociationEn: 'Cancer',
      suit: 'cups',
      imageName: 'cups13.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 35,
      nameTr: 'Kupa Kralı',
      nameEn: 'King of Cups',
      symbol: '🏆',
      astrologicalAssociationTr: 'Balık',
      astrologicalAssociationEn: 'Pisces',
      suit: 'cups',
      imageName: 'cups14.jpg',
      isMajor: false,
    ),

    // ── TILSIMLAR (PENTACLES) ──
    TarotCard(
      id: 36,
      nameTr: 'Tılsım Ası',
      nameEn: 'Ace of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Toprak Elementi',
      astrologicalAssociationEn: 'Earth Element',
      suit: 'pentacles',
      imageName: 'pents01.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 37,
      nameTr: 'Tılsım İkilisi',
      nameEn: 'Two of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Oğlak',
      astrologicalAssociationEn: 'Capricorn',
      suit: 'pentacles',
      imageName: 'pents02.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 38,
      nameTr: 'Tılsım Üçlüsü',
      nameEn: 'Three of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Başak',
      astrologicalAssociationEn: 'Virgo',
      suit: 'pentacles',
      imageName: 'pents03.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 39,
      nameTr: 'Tılsım Dörtlüsü',
      nameEn: 'Four of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Boğa',
      astrologicalAssociationEn: 'Taurus',
      suit: 'pentacles',
      imageName: 'pents04.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 40,
      nameTr: 'Tılsım Beşlisi',
      nameEn: 'Five of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Boğa',
      astrologicalAssociationEn: 'Taurus',
      suit: 'pentacles',
      imageName: 'pents05.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 41,
      nameTr: 'Tılsım Altılısı',
      nameEn: 'Six of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Boğa',
      astrologicalAssociationEn: 'Taurus',
      suit: 'pentacles',
      imageName: 'pents06.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 42,
      nameTr: 'Tılsım Yedilisi',
      nameEn: 'Seven of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Boğa',
      astrologicalAssociationEn: 'Taurus',
      suit: 'pentacles',
      imageName: 'pents07.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 43,
      nameTr: 'Tılsım Sekizlisi',
      nameEn: 'Eight of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Başak',
      astrologicalAssociationEn: 'Virgo',
      suit: 'pentacles',
      imageName: 'pents08.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 44,
      nameTr: 'Tılsım Dokuzlusu',
      nameEn: 'Nine of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Başak',
      astrologicalAssociationEn: 'Virgo',
      suit: 'pentacles',
      imageName: 'pents09.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 45,
      nameTr: 'Tılsım Onlusu',
      nameEn: 'Ten of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Oğlak',
      astrologicalAssociationEn: 'Capricorn',
      suit: 'pentacles',
      imageName: 'pents10.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 46,
      nameTr: 'Tılsım Uşağı',
      nameEn: 'Page of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Toprak Elementi',
      astrologicalAssociationEn: 'Earth Element',
      suit: 'pentacles',
      imageName: 'pents11.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 47,
      nameTr: 'Tılsım Şövalyesi',
      nameEn: 'Knight of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Başak',
      astrologicalAssociationEn: 'Virgo',
      suit: 'pentacles',
      imageName: 'pents12.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 48,
      nameTr: 'Tılsım Kraliçesi',
      nameEn: 'Queen of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Boğa',
      astrologicalAssociationEn: 'Taurus',
      suit: 'pentacles',
      imageName: 'pents13.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 49,
      nameTr: 'Tılsım Kralı',
      nameEn: 'King of Pentacles',
      symbol: '🪙',
      astrologicalAssociationTr: 'Oğlak',
      astrologicalAssociationEn: 'Capricorn',
      suit: 'pentacles',
      imageName: 'pents14.jpg',
      isMajor: false,
    ),

    // ── KILIÇLAR (SWORDS) ──
    TarotCard(
      id: 50,
      nameTr: 'Kılıç Ası',
      nameEn: 'Ace of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Hava Elementi',
      astrologicalAssociationEn: 'Air Element',
      suit: 'swords',
      imageName: 'swords01.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 51,
      nameTr: 'Kılıç İkilisi',
      nameEn: 'Two of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Terazi',
      astrologicalAssociationEn: 'Libra',
      suit: 'swords',
      imageName: 'swords02.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 52,
      nameTr: 'Kılıç Üçlüsü',
      nameEn: 'Three of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Kova',
      astrologicalAssociationEn: 'Aquarius',
      suit: 'swords',
      imageName: 'swords03.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 53,
      nameTr: 'Kılıç Dörtlüsü',
      nameEn: 'Four of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Terazi',
      astrologicalAssociationEn: 'Libra',
      suit: 'swords',
      imageName: 'swords04.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 54,
      nameTr: 'Kılıç Beşlisi',
      nameEn: 'Five of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Kova',
      astrologicalAssociationEn: 'Aquarius',
      suit: 'swords',
      imageName: 'swords05.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 55,
      nameTr: 'Kılıç Altılısı',
      nameEn: 'Six of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'İkizler',
      astrologicalAssociationEn: 'Gemini',
      suit: 'swords',
      imageName: 'swords06.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 56,
      nameTr: 'Kılıç Yedilisi',
      nameEn: 'Seven of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'İkizler',
      astrologicalAssociationEn: 'Gemini',
      suit: 'swords',
      imageName: 'swords07.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 57,
      nameTr: 'Kılıç Sekizlisi',
      nameEn: 'Eight of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'İkizler',
      astrologicalAssociationEn: 'Gemini',
      suit: 'swords',
      imageName: 'swords08.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 58,
      nameTr: 'Kılıç Dokuzlusu',
      nameEn: 'Nine of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'İkizler',
      astrologicalAssociationEn: 'Gemini',
      suit: 'swords',
      imageName: 'swords09.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 59,
      nameTr: 'Kılıç Onlusu',
      nameEn: 'Ten of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'İkizler',
      astrologicalAssociationEn: 'Gemini',
      suit: 'swords',
      imageName: 'swords10.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 60,
      nameTr: 'Kılıç Uşağı',
      nameEn: 'Page of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Hava Elementi',
      astrologicalAssociationEn: 'Air Element',
      suit: 'swords',
      imageName: 'swords11.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 61,
      nameTr: 'Kılıç Şövalyesi',
      nameEn: 'Knight of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'İkizler',
      astrologicalAssociationEn: 'Gemini',
      suit: 'swords',
      imageName: 'swords12.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 62,
      nameTr: 'Kılıç Kraliçesi',
      nameEn: 'Queen of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Terazi',
      astrologicalAssociationEn: 'Libra',
      suit: 'swords',
      imageName: 'swords13.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 63,
      nameTr: 'Kılıç Kralı',
      nameEn: 'King of Swords',
      symbol: '⚔️',
      astrologicalAssociationTr: 'Kova',
      astrologicalAssociationEn: 'Aquarius',
      suit: 'swords',
      imageName: 'swords14.jpg',
      isMajor: false,
    ),

    // ── DEĞNEKLER (WANDS) ──
    TarotCard(
      id: 64,
      nameTr: 'Değnek Ası',
      nameEn: 'Ace of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Ateş Elementi',
      astrologicalAssociationEn: 'Fire Element',
      suit: 'wands',
      imageName: 'wands01.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 65,
      nameTr: 'Değnek İkilisi',
      nameEn: 'Two of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Koç',
      astrologicalAssociationEn: 'Aries',
      suit: 'wands',
      imageName: 'wands02.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 66,
      nameTr: 'Değnek Üçlüsü',
      nameEn: 'Three of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Aslan',
      astrologicalAssociationEn: 'Leo',
      suit: 'wands',
      imageName: 'wands03.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 67,
      nameTr: 'Değnek Dörtlüsü',
      nameEn: 'Four of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Yay',
      astrologicalAssociationEn: 'Sagittarius',
      suit: 'wands',
      imageName: 'wands04.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 68,
      nameTr: 'Değnek Beşlisi',
      nameEn: 'Five of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Aslan',
      astrologicalAssociationEn: 'Leo',
      suit: 'wands',
      imageName: 'wands05.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 69,
      nameTr: 'Değnek Altılısı',
      nameEn: 'Six of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Yay',
      astrologicalAssociationEn: 'Sagittarius',
      suit: 'wands',
      imageName: 'wands06.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 70,
      nameTr: 'Değnek Yedilisi',
      nameEn: 'Seven of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Aslan',
      astrologicalAssociationEn: 'Leo',
      suit: 'wands',
      imageName: 'wands07.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 71,
      nameTr: 'Değnek Sekizlisi',
      nameEn: 'Eight of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Koç',
      astrologicalAssociationEn: 'Aries',
      suit: 'wands',
      imageName: 'wands08.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 72,
      nameTr: 'Değnek Dokuzlusu',
      nameEn: 'Nine of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Koç',
      astrologicalAssociationEn: 'Aries',
      suit: 'wands',
      imageName: 'wands09.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 73,
      nameTr: 'Değnek Onlusu',
      nameEn: 'Ten of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Yay',
      astrologicalAssociationEn: 'Sagittarius',
      suit: 'wands',
      imageName: 'wands10.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 74,
      nameTr: 'Değnek Uşağı',
      nameEn: 'Page of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Ateş Elementi',
      astrologicalAssociationEn: 'Fire Element',
      suit: 'wands',
      imageName: 'wands11.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 75,
      nameTr: 'Değnek Şövalyesi',
      nameEn: 'Knight of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Yay',
      astrologicalAssociationEn: 'Sagittarius',
      suit: 'wands',
      imageName: 'wands12.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 76,
      nameTr: 'Değnek Kraliçesi',
      nameEn: 'Queen of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Koç',
      astrologicalAssociationEn: 'Aries',
      suit: 'wands',
      imageName: 'wands13.jpg',
      isMajor: false,
    ),
    TarotCard(
      id: 77,
      nameTr: 'Değnek Kralı',
      nameEn: 'King of Wands',
      symbol: '🪄',
      astrologicalAssociationTr: 'Aslan',
      astrologicalAssociationEn: 'Leo',
      suit: 'wands',
      imageName: 'wands14.jpg',
      isMajor: false,
    ),
  ];

  /// Tüm 78 Kartın Listesi (Büyük + Küçük Arkana)
  static const List<TarotCard> allCards = [
    ...majorArcana,
    ...minorArcana,
  ];
}
